name: Deploy to Production in AWS DevSecOps

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build the application
      run: npm run build

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo yum update -y
          sudo yum install -y nodejs npm
          sudo npm install -g pm2
          sudo setenforce 0

          cd ~/aula || git clone https://github.com/pedroivoadv/nodepipeline-devops.git ~/aula
          cd ~/aula
          git pull origin main
          npm install
          pm2 delete server || true
          pm2 start server.js
